### ISSUE TITLE
Python: always truncating

### ISSUE THREAD

**Issue by Aurelite** [p-e-w/argos#61]
the output of my python scripts is often shown truncated in some way and i can't figure out why.

```
#!/usr/bin/env python3
a = 12345
b = 54321
print("{} {}|font=monospace size=12".format(a,b))
```

![screenshot from 2018-10-17 19-08-37](https://user-images.githubusercontent.com/34216542/47104154-11e92780-d241-11e8-97d5-0a103c834cd8.png)

adding the `length` attribute with a high value doesn't change anything, while a smaller value shows a different ellipsis
```print("{} {}|font=monospace size=12 lenght=7".format(a,b))```
![screenshot from 2018-10-17 19-09-16](https://user-images.githubusercontent.com/34216542/47104414-abb0d480-d241-11e8-95a8-42c1dbddbe71.png)

i can't see any consistency in the amount truncated either
```print("{}______________{}|font=monospace size=12".format(a,b))```
![screenshot from 2018-10-17 19-10-07](https://user-images.githubusercontent.com/34216542/47104492-def36380-d241-11e8-8baf-9c71193cb70e.png)

I've also tried print( *** , end=None) and sys.stdout.write with the same result

I haven't had these issues with bash scripts, but i'd greatly prefer python for some more complex stuff.

**Comment by apelloni** [comment]
I've just started to use argos and encounter the same problem. 
It is indeed a problem with the space required by different fonts, especially if the new font needs more space than the default one.

I've fixed it for me by changing the default font in argos:

#### `stylesheet.css`
```css {}[stylesheet.css]
.argos-line-view {
  /* Value from the default GNOME Shell theme (class "popup-menu-item") */
  spacing: 12px;
}

.panel-button .argos-line-view {
  /* Value from the default GNOME Shell theme (class "panel-status-menu-box",
     taking into account margin around "app-menu-icon") */
  spacing: 6px;
  font-family: 'monospace'
}

.argos-menu-item-edit {
  font-size: smaller;
}
```

Now it takes the monospace family as a reference and I don't get the `...` anymore
